name: Main

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and maybe publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check secrets available
        run: echo "::set-env name=SECRETS_AVAILABLE::${{ secrets.PASSWORD }}"
      - name: Build
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo Building with password: "${PASSWORD}" "(should be blank on fork)"
          echo Data was:
          cat data
      - name: Publish
        if: env.SECRETS_AVAILABLE
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo Publishing with password: "${PASSWORD}" "(shouldn't happen on fork)"
          echo Data was:
          cat data