name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and maybe publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo Building with password "${PASSWORD}"
          echo Data was:
          cat data